# Generated by Django 4.0.1 on 2022-03-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_remove_coffee_zdjecia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='opis',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='coffee',
            old_name='nazwa',
            new_name='name',
        ),
    ]
