# Generated by Django 4.0.1 on 2022-03-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_rename_opis_coffee_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='type',
            field=models.CharField(choices=[('type_1', 'ARABICA'), ('type_2', 'KAWA MIESZANA'), ('type_3', 'ROBUSTA')], default=2, max_length=10),
            preserve_default=False,
        ),
    ]
