# Generated by Django 4.0.1 on 2022-03-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_coffee_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='type',
            new_name='typeall',
        ),
    ]
