# Generated by Django 4.0.1 on 2022-03-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_rename_type_coffee_typeall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='typeall',
        ),
        migrations.AddField(
            model_name='coffee',
            name='typecoffee',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ARABICA'), (2, 'KAWA MIESZANA'), (3, 'ROBUSTA')], default=1),
            preserve_default=False,
        ),
    ]
