# Generated by Django 4.0.1 on 2022-03-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0008_remove_coffee_typeall_coffee_typecoffee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='typecoffee',
            field=models.CharField(choices=[(1, 'ARABICA'), (2, 'KAWA MIESZANA'), (3, 'ROBUSTA')], max_length=10),
        ),
    ]
