# Generated by Django 4.0.1 on 2022-03-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0009_alter_coffee_typecoffee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='typecoffee',
            field=models.CharField(choices=[('ARABICA', 'ARABICA'), ('KAWA MIESZANA', 'KAWA MIESZANA'), ('ROBUSTA', 'ROBUSTA')], max_length=13),
        ),
    ]
