# Generated by Django 4.0.1 on 2022-03-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0010_alter_coffee_typecoffee'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='zdjecia',
            field=models.ImageField(blank=True, null=True, upload_to='zdjecia'),
        ),
    ]
